#+title: The CAPM
#+author: Matt Brigida, Ph.D.
#+STARTUP: hideblocks
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>

* Overview

- We know how to calculate cash flows and move them around in time given a discount rate.  We also know where to apply these tools---to stock and bond valuation, investment decision rules, etc.  The last step is to figure out how to get the discount rate.  The CAPM will help us do this.
- The CAPM will allow us to /understand what we mean by risk/.  
- The CAPM result: *you are not paid for taking unnecessary risks*.

* Expected Return and Variance

** Single Asset

** Portfolio

Say we have two stocks in our portfolio, $A$ and $B$.  The =Expected Return= of our portfolio is:

$$E(R_p) = w_AE(R_A) + w_BE(R_B)$$

where $w_A$ and $w_B$ are the weights in asset $A$ and $B$ respectively.

The portfolio variance is then:

$$\sigma_p^2 = w^2_A\sigma_A^2 + w^2_B\sigma_B^2 + 2w_Aw_B\sigma_A\sigma_B\rho_{A,B}$$

*** Optional:  Portfolio of Two Assets Video

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/dpB5fx5lbA8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

*  The CAPM, A Short Version

** Realized Returns 

$$R_A = E(R_A) + U_A$$

$$R_A = E(R_A) + m + e_A$$

the key idea is as we for a portfolio, $e_A$, $e_B$, $e_C$, etc cancel each other out.  So via diversification we can remove the unsystematic (firm-specific) risk.

** Systematic Risk Principle

#+begin_quote
An asset's expected return depends only on that asset's systematic (nondiversifiable) risk (not on nondiversifiable risk) (it also depends on other market wide factors).
#+end_quote

The idea is if you don't have to hold the risk, you will not be compensated for doing so.

** Define $\beta$

We'll define $\beta_A$ as the amount of systematic risk in asset /A/ relative to the average asset.  The average asset has a $\beta$ equal to 1.  The average asset is the same as the market.

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/T8WwRI2cyiA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

** The Reward to Risk Ratio

-  $E(R_A) - r_f$ is what we expect to gain from investing in a risky asset $A$ (it is our =reward=).
-  Since we are diversified, our risk from investing in asset $A$ is $\beta_A$.

Thus our =reward-per-unit-risk= (Reward to Risk Ratio) is:

$$\frac{E(R_A) - r_f}{\beta_A}$$

** The CAPM

Via equilibrium argument:

$$\frac{E(R_X) - r_f}{\beta_X} = \frac{E(R_Y) - r_f}{\beta_Y} = E(R_m) - r_f$$

for all capital assets $X$ and $Y$.  

Given the market portfolio is also a capital asset, and $\beta_m = 1$, we have:

$$E(R_X) = r_f + \beta_X(E(R_m) - r_f)$$

for any capital asset $X$.

*** Interpretation

The expected return on any capital asset is a function of:

- $r_f$ the risk free rate, which is *the pure time value of money*.
- $\beta_X$, the amount of systematic risk in the asset $X$.
- $E(R_m) - r_f$, the *market risk premium*, which is the market-wide cost of bearing a unit of systematic risk.

So you can read the CAPM as:

#+begin_quote
The expected return on any asset is equal to the pure time value of money plus the product of the amount of systematic risk in the asset and the cost of systematic risk.
#+end_quote

*** Stock with low correlations...

Stock with low amount of systematic risk will have low beta coefficients ($\beta_X = \frac{Cov(R_X, R_m)}{\sigma^2_m}$) and thus will have low expected returns.  That is, you only require low returns for assets that serve as a market hedge.  Remember:

#+begin_quote
An asset's risk is not its standard deviation, but in how much that asset increases your portfolio's standard deviation when it is added (which is the $\beta$).
#+end_quote





* Insights from the CAPM

- A Risky Stock Can Make Your Portfolio Safer


** The effect of correlation on portfolio risk

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://micfm.shinyapps.io/The_CAPM_app1/"> </iframe>
#+END_EXPORT

* Applied CAPM: Calculating Beta (server may be down)

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://micfm.shinyapps.io/The_CAPM_app2/"></iframe>
#+END_EXPORT

Estimating beta in R.

#+begin_src R :exports both :session r_beta
library(quantmod)

tsla <- getSymbols("tsla", auto.assign=FALSE)
spy <- getSymbols("spy", auto.assign=FALSE)  # spy is an ETF traching the S&P 500 (the market)

tsla_returns <- Delt(Ad(tsla['2020/'])) # just use 2020 forward
spy_returns <- Delt(Ad(spy['2020/']))

beta <- round(lm(tsla_returns ~ spy_returns)$coef[2], 2)  # the beta coefficient
beta
#+end_src

#+RESULTS:
: 1.39

So TSLA's beta coefficient since 2020 is src_R[:session r_beta]{beta} {{{results(=1.39=)}}}.


* Optional: A CAPM video appropriate to an Intro to Finance Course 

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/5vQL-50itig" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT


* Optional: A slightly more advanced treatment of the CAPM
  

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/coJl_aCBTuA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

